"""Exit codes — stable compatibility surface (Spec §23)."""

SUCCESS = 0
INVALID_ARGS = 2

INVALID_INPUT = 10
UNSUPPORTED_AUDIO_STREAM = 11

FFPROBE_FAILURE = 20
FFMPEG_FAILURE = 21

RUNTIME_UNAVAILABLE = 30
CUDA_UNAVAILABLE = 31
CUDA_OOM = 32
MODEL_MISSING = 33

ASR_FAILURE = 40
ALIGNMENT_FAILURE = 41
TIMESTAMP_VALIDATION_FAILURE = 42

PROJECT_FAILURE = 50
EXPORT_FAILURE = 51

CANCELED = 130
